name: Prepare MacOS

description: Prepare MacOS

runs:
  using: "composite"
    
  steps:
  - name: Install dependencies
    run: |
      brew update
      brew install gcc make autoconf automake libtool texinfo
    shell: bash

  - name: Report
    run: |
      echo "MacOS brew prepared"
    shell: bash
