.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EGEL" "1" "September 2021" "" ""
.
.SH "NAME"
\fBegel\fR \- an interpreted, interactive, eager\-combinator language
.
.SH "SYNOPSIS"
\fBegel\fR [\-|\-\-interact] [\-I \fIpath\fR|\-\-include \fIpath\fR] [\fIfile\fR]
.
.P
\fBegel\fR [\-I \fIpath\fR|\-\-include \fIpath\fR] \-e \fIcommand\fR
.
.P
\fBegel\fR [\-h|\-\-help|\-v|\-\-version]
.
.SH "DESCRIPTION"
Egel is an interpreted, interactive, eager\-combinator programming language that combines remarkable power with very clear syntax\.
.
.P
A short tutorial as in introduction into the language is given below\.
.
.P
Egel\'s basic power can be extended with your own modules written in C++\. Those modules are dynamically loaded\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints brief usage information, may list debug options\.
.
.TP
\fB\-\fR, \fB\-\-interact\fR
Enter interactive mode unconditionally\.
.
.TP
\fB\-e\fR, \fB\-\-eval <command>\fR
Evaluate the given command\.
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Prints the current version number\.
.
.TP
\fB\-I\fR, \fB\-\-include <path>\fR
Add an include path\.
.
.SH "TUTORIAL"
Below, a short introduction to the Egel language is given\.
.
.SS "Expressions"
Egel programs consist of expression which are evaluated eagerly\.
.
.IP "\(bu" 4
Basic primitive types are integers, floats, unicode characters, and unicode strings\.
.
.IP
\fB0 1 2\fR , \fB0\.0 3\.14 \-1\.2\fR , \fB\'a\'\fR \fB\'∀\'\fR , or \fB"Hello World!"\fR
.
.IP "\(bu" 4
All constants compose\.
.
.IP
\fB(0 1)\fR is just as legal as \fB(cons \'a\' nil)\fR
.
.IP "\(bu" 4
Rewriting is done with the pattern\-matching abstraction, uppercase letters denote variables\.
.
.IP
\fB[ X \-> X ]\fR , \fB[ (cons HEAD TAIL) \-> HEAD ]\fR
.
.IP
The abstraction consists of a number of matches, it may be variadic without penalty\.
.
.IP
\fB[ X Y \-> 2 | X \-> 1 | \-> 0]\fR
.
.IP "\(bu" 4
Patterns may hold rudimentary type matches\.
.
.IP
\fB[ I::int \-> "an int" | C::cons \-> "a cons" ]\fR
.
.IP "\(bu" 4
Let expressions assign values to intermediateries\.
.
.IP
\fBlet X = 1 + 2 in X * X\fR
.
.IP "\(bu" 4
A semicolon separates computations\.
.
.IP
\fBprint (1+2); "done"\fR
.
.IP "\(bu" 4
Exception handling is supported, any value may be thrown and caught\.
.
.IP
\fBtry 1 + throw "failure" catch [ EXC \-> print EXC ]\fR
.
.IP "\(bu" 4
Parallell programming is achieved through the \fBpar\fR and \fBproc\fR abstractions\. A \fBpar\fR starts two computations in parallel and returns a tuple of both values after both complete\.
.
.IP
\fBpar [ _ \-> _computation0_ ] [ _ \-> _computation1_ ]\fR
.
.IP
The process abstraction is not discussed here\.
.
.IP "\(bu" 4
Formatting strings is handled with the \fBformat\fR combinator, see \fIhttps://fmt\.dev/\fR\.
.
.IP
\fBprint (format "Hello {}" "world")\fR
.
.IP "" 0
.
.SS "Modules"
A module is a series of combinator declarations possibly encapsulated in a namespace\. All combinators are named lowercase, there is some provisional support for unicode\. Modules may import each other\. The \fBmain\fR combinator of the top module drives all computation when present\.
.
.P
Tying it all together:
.
.IP "" 4
.
.nf

# A parallel fibonnaci implementation\.

import "prelude\.eg"

namespace Fibonnaci (
  using System

  def fib =
    [ 0 \-> 0
    | 1 \-> 1
    | N \-> fib (N\- 2) + fib (N\- 1) ]

  def pfib =
    [ 0 \-> 0
    | 1 \-> 1
    | X \-> [ (F0, F1) \-> F0 + F1 ]
           (par [Y \-> pfib (X \- 1) ] [Z\-> pfib (X \- 2)]) ]

)

using System

def main = Fibonnaci:pfib (3+2)
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
There are three modes in which the interpreter is used: batch, interactive, or command mode\.
.
.P
In batch mode, just supply the top module with a \fBmain\fR combinator\.
.
.IP "" 4
.
.nf

$ egel helloworld\.eg
Hello world!
.
.fi
.
.IP "" 0
.
.P
The interpreter will start in interactive mode when invoked without a module argument\.
.
.IP "" 4
.
.nf

$ egel
> using System
> 1 + 1
2
.
.fi
.
.IP "" 0
.
.P
Supply a command to use \fBegel \-e\fR as a simple calculator\.
.
.IP "" 4
.
.nf

$ egel \-e "1+1"
2
.
.fi
.
.IP "" 0
.
.SH "FILES"
The following files should be in the \fBEGEL_INCLUDE\fR directory\.
.
.TP
\fBprelude\.eg\fR
The standard Egel prelude\.
.
.TP
\fBio\.ego\fR \fBregex\.ego\fR
Standard input/output, regexes dynamic libraries\.
.
.SH "ENVIRONMENT"
.
.TP
\fBEGEL_INCLUDE\fR
The path to the standard include directory\.
.
.TP
\fBEGEL_PS0\fR
The prompt given by the interpreter in interactive mode\.
.
.SH "BUGS"
See GitHub Issues: \fIhttps://github\.com/egel\-lang/egel/issues\fR
.
.SH "AUTHOR"
M\.C\.A\. (Marco) Devillers \fImarco\.devillers@gmail\.com\fR
.
.SH "SEE ALSO"
\fBc++(1)\fR
