name: Lightning leech

description: steal Lightning from brew

runs:
  using: "composite"
    
  steps:
  - name: Checkout Lightning 
    run: |
      echo "WARNING: stealing lightning from brew!"
      echo "This is not recommended, despite brew,"
      echo "MacOS is _not_ a Linux and build from"
      echo "sources is preferred."
      echo "However, libffi fails to compile on the"
      echo "MacOS runner."
      brew install lightning
    shell: bash

  - name: Install Lightning
    run: |
      mkdir -p {{github.workspace}}/vendor/local
      mkdir -p {{github.workspace}}/vendor/local/include
      mkdir -p {{github.workspace}}/vendor/local/lib
      echo "copying into vendor/local"
      cp -r /opt/homebrew/opt/lightning/include/* {{github.workspace}}/vendor/local/include
      cp -r /opt/homebrew/opt/lightning/lib/* {{github.workspace}}/vendor/local/lib
      echo "vendor/local/include"
      ls -la {{github.workspace}}/vendor/local/include
      echo "vendor/local/lib"
      ls -la {{github.workspace}}/vendor/local/lib
    shell: bash
