name: ICU4C

description: Build and Install ICU4C

runs:
  using: "composite"
    
  steps:
  - name: Install dependencies
    run: |
      brew install make
    shell: bash

  - name: Checkout ICU source
    run: |
      git submodule update --init --recursive ./vendor/icu
    shell: bash

  - name: Configure ICU
    run: |
      export CFLAGS="-fPIC"
      export CXXFLAGS="-fPIC"
      ls -la
      pushd vendor/icu/icu4c/source
      chmod +x runConfigureICU configure install-sh
      ./runConfigureICU MacOSX --enable-static --prefix=$(realpath "../../../local")
      popd
    shell: bash

  - name: Compile ICU
    run: |
      export CFLAGS="-fPIC"
      export CXXFLAGS="-fPIC"
      pushd vendor/icu/icu4c/source
      export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
      make --enable-static
      popd
    shell: bash

  - name: Install ICU
    run: |
      pushd vendor/icu/icu4c/source
      export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
      make install PREFIX="../../../local"
      popd
    shell: bash
