name: MacOS Tar Artefact

description: Create an MacOS Tar Artefact

runs:
  using: "composite"
    
  steps:
  - name: Determine tar package name
    id: tarname
    run: |
      egelversion=`contrib/scripts/version.sh src/egel.cpp`
      echo "TARNAME=egel-macos-$egelversion" >> $GITHUB_OUTPUT
    shell: bash

  - name: Create tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "creating: $tarname"
      lib0=`find vendor/local/lib -name "liblightning.?.dylib" -print -quit`
      lib1=`find vendor/local/lib -name "libfmt.??.dylib" -print -quit`
      lib2=`find vendor/local/lib -name "libffi.?.dylib" -print -quit`
      lib3=`find vendor/local/lib -name "libicui18n.??.dylib" -print -quit`
      lib4=`find vendor/local/lib -name "libicuio.??.dylib" -print -quit`
      lib5=`find vendor/local/lib -name "libicutu.??.dylib" -print -quit`
      lib6=`find vendor/local/lib -name "libicudata.??.dylib" -print -quit`
      lib7=`find vendor/local/lib -name "libicuuc.??.dylib" -print -quit`
      contrib/scripts/tarpackage.sh $tarname . $lib0 $lib1 $lib2 $lib3 $lib4 $lib5 $lib6 $lib7
    shell: bash

  - name: List tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "contents of created $tarname"
      tar -tf $tarname.tgz
    shell: bash

  - name: Upload artefact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ steps.tarname.outputs.TARNAME }}
      path: ${{ steps.tarname.outputs.TARNAME }}.tgz

