name: Prepare Ubuntu

description: Prepare Ubuntu

runs:
  using: "composite"
    
  steps:
  - name: Install dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y build-essential autoconf automake libtool texinfo
    shell: bash

  - name: Checkout code
    run: |
      sudo apt-get install -y libicu-dev
      sudo apt-get install -y libfmt-dev
      sudo apt-get install -y libffi-dev
    shell: bash

  - name: Report
    run: |
      echo "Ubuntu prepared"
    shell: bash
