name: GNU Lightning

description: Build and Install GNU Lightning

runs:
  using: "composite"
    
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Install dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y build-essential autoconf automake libtool texinfo
    shell: bash

  - name: Download GNU Lightning source
    run: |
      wget https://ftp.gnu.org/gnu/lightning/lightning-2.2.3.tar.gz
      tar -xzvf lightning-2.2.3.tar.gz
    shell: bash

  - name: Configure GNU Lightning
    run: |
      pushd lightning-2.2.3
      ./configure
      popd
    shell: bash

  - name: Compile GNU Lightning
    run: |
      pushd lightning-2.2.3
      make
      popd
    shell: bash

  - name: Install GNU Lightning
    run: |
      pushd lightning-2.2.3
      sudo make install
      popd
    shell: bash
