name: GNU Lightning

description: Build and Install GNU Lightning

runs:
  using: "composite"
    
  steps:
  - name: Checkout GNU Lightning source
    run: |
      git submodule update --init --recursive ./vendor/lightning
    shell: bash

  - name: Configure GNU Lightning
    run: |
      pushd vendor/lightning
      ls -la
      ./bootstrap
      ./configure
      popd
    shell: bash

  - name: Compile GNU Lightning
    run: |
      pushd vendor/lightning
      make
      popd
    shell: bash

  - name: Install GNU Lightning
    run: |
      pushd vendor/lightning
      sudo make install
      popd
    shell: bash
