name: GNU Lightning

description: Build and Install GNU Lightning

runs:
  using: "composite"
    
  steps:
  - name: Install dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y build-essential autoconf automake libtool texinfo
    shell: bash

  - name: Checkout GNU Lightning source
    run: |
      pushd vendor/lightning
      git checkout --recurse-submodules
      popd
    shell: bash

  - name: Configure GNU Lightning
    run: |
      pushd vendor/lightning
      ./bootstrap
      ./configure
      popd
    shell: bash

  - name: Compile GNU Lightning
    run: |
      pushd vendor/lightning
      make
      popd
    shell: bash

  - name: Install GNU Lightning
    run: |
      pushd vendor/lightning
      sudo make install
      popd
    shell: bash
