name: Ubuntu Tar Artefact

description: Create an Ubuntu Tar Artefact

runs:
  using: "composite"
    
  steps:
  - name: Determine tar package name
    id: tarname
    run: |
      egelversion=`contrib/scripts/version.sh src/egel.cpp`
      echo "TARNAME=egel-ubuntu-$egelversion" >> $GITHUB_OUTPUT
    shell: bash

  - name: Create tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "creating: $tarname"
      contrib/scripts/tarpackage.sh $tarname . /usr/local/lib/liblightning*.so
    shell: bash

  - name: List tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "contents of created $tarname"
      tar -tf $tarname.tgz
    shell: bash

  - name: Upload artefact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ steps.tarname.outputs.TARNAME }}
      path: ${{ steps.tarname.outputs.TARNAME }}.tgz

  - name: Release
    uses: actions/create-release@v1
    id: create_release
    with:
      draft: true
      prerelease: true
      release_name: ${{ steps.tarname.outputs.TARNAME }}
      tag_name: ${{ github.ref }}
      body_path: PREBUILT.md
    env:
      GITHUB_TOKEN: ${{ github.token }}

  - name: Upload Ubuntu artefact
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ github.token }}
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: ${{ steps.tarname.outputs.TARNAME }}.tgz
      asset_name: ${{ steps.tarname.outputs.TARNAME }}.tgz
      asset_content_type: application/gzip
