name: Ubuntu Tar Artefact

description: Create an Ubuntu Tar Artefact

runs:
  using: "composite"
    
  steps:
  - name: Determine tar package name
    id: tarname
    run: |
      egelversion=`contrib/scripts/version.sh src/egel.cpp`
      echo "TARNAME=egel-ubuntu-$egelversion" >> $GITHUB_OUTPUT
    shell: bash

  - name: Create tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "creating: $tarname"
      lib0=`find /usr/lib /usr/lib64/ /usr/local/lib /usr/local/lib64 -name "liblightning.so.?" -print -quit`
      lib1=`find /usr/lib /usr/lib64/ /usr/local/lib /usr/local/lib64 -name "libfmt.so.?" -print -quit`
      lib2=`find /usr/lib /usr/lib64/ /usr/local/lib /usr/local/lib64 -name "libffi.so.?" -print -quit`
      lib3=`find /usr/lib /usr/lib64/ /usr/local/lib /usr/local/lib64 -name "libicui18n.so.??" -print -quit`
      lib4=`find /usr/lib /usr/lib64/ /usr/local/lib /usr/local/lib64 -name "libicuio.so.??" -print -quit`
      lib5=`find /usr/lib /usr/lib64/ /usr/local/lib /usr/local/lib64 -name "libicutu.so.??" -print -quit`
      lib6=`find /usr/lib /usr/lib64/ /usr/local/lib /usr/local/lib64 -name "libicudata.so.??" -print -quit`
      lib7=`find /usr/lib /usr/lib64/ /usr/local/lib /usr/local/lib64 -name "libicuuc.so.??" -print -quit`
      contrib/scripts/tarpackage.sh $tarname . $lib0 $lib1 $lib2 $lib3 $lib4 $lib5 $lib6 $lib7
    shell: bash

  - name: List tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "contents of created $tarname"
      tar -tf $tarname.tgz
    shell: bash

  - name: Upload artefact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ steps.tarname.outputs.TARNAME }}
      path: ${{ steps.tarname.outputs.TARNAME }}.tgz

