name: Ubuntu Tar Artefact

description: Create an Ubuntu Tar Artefact

runs:
  using: "composite"
    
  steps:
  - name: Determine tar package name
    id: tarname
    run: |
      egelversion=`contrib/scripts/version.sh src/egel.cpp`
      echo "TARNAME=egel-ubuntu-$egelversion" >> $GITHUB_OUTPUT
    shell: bash

  - name: Create tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "creating: $tarname"
      contrib/scripts/tarpackage.sh $tarname . *.md /usr/local/lib/liblightning*.so
    shell: bash

  - name: List tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "contents of created $tarname"
      tar -tf $tarname.tgz
    shell: bash

  - name: Upload artefact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ steps.tarname.outputs.TARNAME }}
      path: ${{ steps.tarname.outputs.TARNAME }}.tgz
