name: Ubuntu Tar Artefact

description: Create an Ubuntu Tar Artefact

runs:
  using: "composite"
    
  steps:
  - name: Determine tar package name
    id: tarname
    run: |
      egelversion=`contrib/scripts/version.sh src/egel.cpp`
      echo "::set-output name=TARNAME::egel-ubuntu-$egelversion"
    shell: bash

  - name: Create tar package
    run: |
      tarname=${{ steps.tarname.outputs.TARNAME }}
      echo "creating: $tarname"
      contrib/scripts/tarpackage.sh $tarname .
    shell: bash

  - name: Upload artefact
    uses: actions/upload-artifact@v3
    with:
      name: ${{ steps.tarname.outputs.TARNAME }}
      path: ${{ steps.tarname.outputs.TARNAME }}.tgz
