name: FFI

description: Build and Install FFI

runs:
  using: "composite"
    
  steps:
  - name: Install dependencies
    run: |
      brew install gcc libtool make autoconf automake texinfo
    shell: bash

  - name: Checkout FFI source
    run: |
      git submodule update --init --recursive ./vendor/libffi
      pushd vendor/libffi
      git checkout v3.4.2
      popd
    shell: bash

  - name: Configure FFI
    run: |
      export CFLAGS="-fPIC"
      export CXXFLAGS="-fPIC"
      export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
      pushd vendor/libffi
      ls -la
      autoupdate
      ./configure --prefix=$(realpath "../local")
      make
      popd
    shell: bash

  - name: Compile FFI
    run: |
      export CFLAGS="-fPIC"
      export CXXFLAGS="-fPIC"
      export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
      pushd vendor/libffi
      make
      popd
    shell: bash

  - name: Install FFI
    #if: always()
    run: |
      export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
      pushd vendor/libffi
      make install
      popd
    shell: bash
