name: FFI

description: Build and Install FFI

runs:
  using: "composite"
    
  steps:
  - name: Install dependencies
    run: |
      brew install gcc make autoconf automake libtool texinfo
    shell: bash

  - name: Checkout FFI source
    run: |
      git submodule update --init --recursive ./vendor/libffi
      pushd vendor/libffi
      git checkout v3.4.2
      popd
    shell: bash

  - name: Configure FFI
    run: |
      export CFLAGS="-fPIC"
      export CXXFLAGS="-fPIC"
      export PATH="$HOMEBREW_PREFIX/opt/make/libtool/libexec/gnubin:$PATH"
      pushd vendor/libffi
      #ls -la
      #ls /opt/homebrew/Cellar/libtool/2.4.7/share/aclocal
      #export LIBTOOL=`which glibtool`
      #export LIBTOOLIZE=`which glibtoolize`
      #export ACLOCAL_PATH=/opt/homebrew/Cellar/libtool/2.4.7/share/aclocal:$ACLOCAL_PATH
      echo "path:          " $LIBTOOL
      #echo "libtool:      " $LIBTOOL
      #echo "libtoolize:   " $LIBTOOLIZE
      #echo "aclocal path: " $ACLOCAL_PATH
      ./autogen.sh
      ./configure
      popd
    shell: bash

  - name: Compile FFI
    run: |
      export CFLAGS="-fPIC"
      export CXXFLAGS="-fPIC"
      export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
      pushd vendor/libffi
      make
      popd
    shell: bash

  - name: Install FFI
    #if: always()
    run: |
      export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
      pushd vendor/libffi
      make install DESTDIR="../local"
      popd
    shell: bash
