name: Build MacOS

on:
  workflow_call:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          echo
          echo github.workspace: ${{ github.workspace }}
          echo env.BUILD_TYPE: ${{ env.BUILD_TYPE }}
          echo "MACOS DOESN'T BUILD AT THE MOMENT"
          exit 1

      - name: Make local dir
        run: |
          mkdir vendor/local

      - name: Build GNU Lightning static lib
        uses: ./.github/actions/macos-lightning

      - name: Build FFI static lib
        uses: ./.github/actions/macos-ffi

      - name: Build FMT static lib
        uses: ./.github/actions/macos-fmt

      - name: Build ICU static lib
        uses: ./.github/actions/macos-icu

      - name: Link static cmake
        run: |
          rm -rf CMakeLists.txt
          ln -s CMakeLists.static CMakeLists.txt

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./egel -v
