name: Build MacOS

on:
  workflow_call:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          echo
          echo github.workspace: ${{ github.workspace }}
          echo env.BUILD_TYPE: ${{ env.BUILD_TYPE }}
        shell: bash

      - name: Fail
        run: |
          echo "Fail when testing other builds"
          #exit 1
        shell: bash

      - name: Prepare
        uses: ./.github/actions/macos-prepare

      - name: Make local dir
        run: |
          mkdir vendor/local
        shell: bash

      - name: Build FFI static lib
        uses: ./.github/actions/macos-ffi-leech

      - name: Build GNU Lightning static lib
        uses: ./.github/actions/macos-lightning

      - name: Build FMT static lib
        uses: ./.github/actions/macos-fmt

      - name: Build ICU static lib
        uses: ./.github/actions/macos-icu

      - name: Link vendor cmake
        run: |
          rm -rf CMakeLists.txt
          ln -s CMakeLists.vendor CMakeLists.txt
        shell: bash

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: bash

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        shell: bash

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./egel -v
        shell: bash

      - name: Create tar
        uses: ./.github/actions/macos-tar
