name: Build Ubuntu-x86_64

on:
  workflow_call:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          echo
          echo github.workspace: ${{ github.workspace }}
          echo env.BUILD_TYPE: ${{ env.BUILD_TYPE }}
        shell: bash

      - name: Fail
        run: |
          echo "We fail when testing other builds"
          exit 1
        shell: bash

      - name: Checkout code
        uses: ./.github/actions/ubuntu-prepare

      - name: Install GNU lightning
        uses: ./.github/actions/ubuntu-lightning

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: bash

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./egel -v
        shell: bash

      - name: Create Ubuntu artefact
        uses: ./.github/actions/ubuntu-tar

